name: Keep Render Awake

on:
  schedule:
    - cron: "*/7 * * * *"  # cada 5 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render site
        run: curl -I https://brincolin.onrender.com/